<?php

namespace ContainerCcCBPzB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bay5P5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bay_5P5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'patient' => ['privates', '.errored..service_locator.Bay_5P5.App\\Entity\\Patient', NULL, 'Cannot autowire service ".service_locator.Bay_5P5": it needs an instance of "App\\Entity\\Patient" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'patient' => 'App\\Entity\\Patient',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.Bay_5P5'])) {
            return $container->privates['.service_locator.Bay_5P5'];
        }

        return $container->privates['.service_locator.Bay_5P5'] = $instance;
    }
}
