<?php

namespace ContainerCcCBPzB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YxywPFa.App\Controller\RDVController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rdv' => ['privates', '.errored..service_locator.YxywPFa.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.YxywPFa": it needs an instance of "App\\Entity\\RDV" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'rdv' => 'App\\Entity\\RDV',
            'em' => '?',
        ]))->withContext('App\\Controller\\RDVController::delete()', $container);

        if (isset($container->privates['.service_locator.YxywPFa.App\\Controller\\RDVController::delete()'])) {
            return $container->privates['.service_locator.YxywPFa.App\\Controller\\RDVController::delete()'];
        }

        return $container->privates['.service_locator.YxywPFa.App\\Controller\\RDVController::delete()'] = $instance;
    }
}
