<?php

namespace ContainerCcCBPzB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDV2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YxywPFa.App\Entity\RDV' shared service.
     *
     * @return \App\Entity\RDV
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YxywPFa": it needs an instance of "App\\Entity\\RDV" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
