<?php

namespace ContainerWeh8fci;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QvJvkQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qv_jvkQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qv_jvkQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'patient' => ['privates', '.errored..service_locator.qv_jvkQ.App\\Entity\\Patient', NULL, 'Cannot autowire service ".service_locator.qv_jvkQ": it needs an instance of "App\\Entity\\Patient" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'patient' => 'App\\Entity\\Patient',
        ]);
    }
}
