<?php

namespace ContainerWeh8fci;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MQ0wzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m_Q_0wz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctor' => ['privates', '.errored..service_locator.m_Q_0wz.App\\Entity\\Doctor', NULL, 'Cannot autowire service ".service_locator.m_Q_0wz": it needs an instance of "App\\Entity\\Doctor" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'doctor' => 'App\\Entity\\Doctor',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.m_Q_0wz'])) {
            return $container->privates['.service_locator.m_Q_0wz'];
        }

        return $container->privates['.service_locator.m_Q_0wz'] = $instance;
    }
}
