<?php

namespace ContainerWeh8fci;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sEQP2tc.App\Controller\DoctorController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sEQP2tc.App\\Controller\\DoctorController::show()'] = ($container->privates['.service_locator.sEQP2tc'] ?? $container->load('get_ServiceLocator_SEQP2tcService'))->withContext('App\\Controller\\DoctorController::show()', $container);
    }
}
