<?php

namespace ContainerWeh8fci;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.awDVtsM.App\Controller\RDVController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.awDVtsM.App\\Controller\\RDVController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rdv' => ['privates', '.errored..service_locator.awDVtsM.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.awDVtsM": it needs an instance of "App\\Entity\\RDV" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'rdv' => 'App\\Entity\\RDV',
        ]))->withContext('App\\Controller\\RDVController::show()', $container);
    }
}
