<?php

namespace ContainerWeh8fci;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xtygkzl.App\Controller\RDVController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
        ], [
            'em' => '?',
            'doctorRepository' => 'App\\Repository\\DoctorRepository',
            'patientRepository' => 'App\\Repository\\PatientRepository',
        ]))->withContext('App\\Controller\\RDVController::new()', $container);

        if (isset($container->privates['.service_locator.Xtygkzl.App\\Controller\\RDVController::new()'])) {
            return $container->privates['.service_locator.Xtygkzl.App\\Controller\\RDVController::new()'];
        }

        return $container->privates['.service_locator.Xtygkzl.App\\Controller\\RDVController::new()'] = $instance;
    }
}
