<?php

namespace ContainerXJV1m8A;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FCJfrODService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fCJfrOD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\DoctorController::index' => ['privates', '.service_locator.BnC8870.App\\Controller\\DoctorController::index()', 'getDoctorControllerindexService', true],
            'App\\Controller\\DoctorController::show' => ['privates', '.service_locator.sEQP2tc.App\\Controller\\DoctorController::show()', 'getDoctorControllershowService', true],
            'App\\Controller\\DoctorController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\DoctorController::new()', 'getDoctorControllernewService', true],
            'App\\Controller\\DoctorController::edit' => ['privates', '.service_locator.m_Q_0wz.App\\Controller\\DoctorController::edit()', 'getDoctorControllereditService', true],
            'App\\Controller\\DoctorController::delete' => ['privates', '.service_locator.m_Q_0wz.App\\Controller\\DoctorController::delete()', 'getDoctorControllerdeleteService', true],
            'App\\Controller\\DoctorController::rdvs' => ['privates', '.service_locator.sEQP2tc.App\\Controller\\DoctorController::rdvs()', 'getDoctorControllerrdvsService', true],
            'App\\Controller\\PatientController::index' => ['privates', '.service_locator.bLDxsdf.App\\Controller\\PatientController::index()', 'getPatientControllerindexService', true],
            'App\\Controller\\PatientController::show' => ['privates', '.service_locator.qv_jvkQ.App\\Controller\\PatientController::show()', 'getPatientControllershowService', true],
            'App\\Controller\\PatientController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\PatientController::new()', 'getPatientControllernewService', true],
            'App\\Controller\\PatientController::edit' => ['privates', '.service_locator.Bay_5P5.App\\Controller\\PatientController::edit()', 'getPatientControllereditService', true],
            'App\\Controller\\PatientController::delete' => ['privates', '.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()', 'getPatientControllerdeleteService', true],
            'App\\Controller\\PatientController::rdvs' => ['privates', '.service_locator.qv_jvkQ.App\\Controller\\PatientController::rdvs()', 'getPatientControllerrdvsService', true],
            'App\\Controller\\RDVController::index' => ['privates', '.service_locator.spZWi_P.App\\Controller\\RDVController::index()', 'getRDVControllerindexService', true],
            'App\\Controller\\RDVController::show' => ['privates', '.service_locator.awDVtsM.App\\Controller\\RDVController::show()', 'getRDVControllershowService', true],
            'App\\Controller\\RDVController::new' => ['privates', '.service_locator.Xtygkzl.App\\Controller\\RDVController::new()', 'getRDVControllernewService', true],
            'App\\Controller\\RDVController::edit' => ['privates', '.service_locator.8AS6cEJ.App\\Controller\\RDVController::edit()', 'getRDVControllereditService', true],
            'App\\Controller\\RDVController::delete' => ['privates', '.service_locator.YxywPFa.App\\Controller\\RDVController::delete()', 'getRDVControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\DoctorController:index' => ['privates', '.service_locator.BnC8870.App\\Controller\\DoctorController::index()', 'getDoctorControllerindexService', true],
            'App\\Controller\\DoctorController:show' => ['privates', '.service_locator.sEQP2tc.App\\Controller\\DoctorController::show()', 'getDoctorControllershowService', true],
            'App\\Controller\\DoctorController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\DoctorController::new()', 'getDoctorControllernewService', true],
            'App\\Controller\\DoctorController:edit' => ['privates', '.service_locator.m_Q_0wz.App\\Controller\\DoctorController::edit()', 'getDoctorControllereditService', true],
            'App\\Controller\\DoctorController:delete' => ['privates', '.service_locator.m_Q_0wz.App\\Controller\\DoctorController::delete()', 'getDoctorControllerdeleteService', true],
            'App\\Controller\\DoctorController:rdvs' => ['privates', '.service_locator.sEQP2tc.App\\Controller\\DoctorController::rdvs()', 'getDoctorControllerrdvsService', true],
            'App\\Controller\\PatientController:index' => ['privates', '.service_locator.bLDxsdf.App\\Controller\\PatientController::index()', 'getPatientControllerindexService', true],
            'App\\Controller\\PatientController:show' => ['privates', '.service_locator.qv_jvkQ.App\\Controller\\PatientController::show()', 'getPatientControllershowService', true],
            'App\\Controller\\PatientController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\PatientController::new()', 'getPatientControllernewService', true],
            'App\\Controller\\PatientController:edit' => ['privates', '.service_locator.Bay_5P5.App\\Controller\\PatientController::edit()', 'getPatientControllereditService', true],
            'App\\Controller\\PatientController:delete' => ['privates', '.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()', 'getPatientControllerdeleteService', true],
            'App\\Controller\\PatientController:rdvs' => ['privates', '.service_locator.qv_jvkQ.App\\Controller\\PatientController::rdvs()', 'getPatientControllerrdvsService', true],
            'App\\Controller\\RDVController:index' => ['privates', '.service_locator.spZWi_P.App\\Controller\\RDVController::index()', 'getRDVControllerindexService', true],
            'App\\Controller\\RDVController:show' => ['privates', '.service_locator.awDVtsM.App\\Controller\\RDVController::show()', 'getRDVControllershowService', true],
            'App\\Controller\\RDVController:new' => ['privates', '.service_locator.Xtygkzl.App\\Controller\\RDVController::new()', 'getRDVControllernewService', true],
            'App\\Controller\\RDVController:edit' => ['privates', '.service_locator.8AS6cEJ.App\\Controller\\RDVController::edit()', 'getRDVControllereditService', true],
            'App\\Controller\\RDVController:delete' => ['privates', '.service_locator.YxywPFa.App\\Controller\\RDVController::delete()', 'getRDVControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DoctorController::index' => '?',
            'App\\Controller\\DoctorController::show' => '?',
            'App\\Controller\\DoctorController::new' => '?',
            'App\\Controller\\DoctorController::edit' => '?',
            'App\\Controller\\DoctorController::delete' => '?',
            'App\\Controller\\DoctorController::rdvs' => '?',
            'App\\Controller\\PatientController::index' => '?',
            'App\\Controller\\PatientController::show' => '?',
            'App\\Controller\\PatientController::new' => '?',
            'App\\Controller\\PatientController::edit' => '?',
            'App\\Controller\\PatientController::delete' => '?',
            'App\\Controller\\PatientController::rdvs' => '?',
            'App\\Controller\\RDVController::index' => '?',
            'App\\Controller\\RDVController::show' => '?',
            'App\\Controller\\RDVController::new' => '?',
            'App\\Controller\\RDVController::edit' => '?',
            'App\\Controller\\RDVController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DoctorController:index' => '?',
            'App\\Controller\\DoctorController:show' => '?',
            'App\\Controller\\DoctorController:new' => '?',
            'App\\Controller\\DoctorController:edit' => '?',
            'App\\Controller\\DoctorController:delete' => '?',
            'App\\Controller\\DoctorController:rdvs' => '?',
            'App\\Controller\\PatientController:index' => '?',
            'App\\Controller\\PatientController:show' => '?',
            'App\\Controller\\PatientController:new' => '?',
            'App\\Controller\\PatientController:edit' => '?',
            'App\\Controller\\PatientController:delete' => '?',
            'App\\Controller\\PatientController:rdvs' => '?',
            'App\\Controller\\RDVController:index' => '?',
            'App\\Controller\\RDVController:show' => '?',
            'App\\Controller\\RDVController:new' => '?',
            'App\\Controller\\RDVController:edit' => '?',
            'App\\Controller\\RDVController:delete' => '?',
        ]);

        if (isset($container->privates['.service_locator.fCJfrOD'])) {
            return $container->privates['.service_locator.fCJfrOD'];
        }

        return $container->privates['.service_locator.fCJfrOD'] = $instance;
    }
}
