<?php

namespace ContainerXJV1m8A;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPatientControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bLDxsdf.App\Controller\PatientController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bLDxsdf.App\\Controller\\PatientController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
        ], [
            'patientRepository' => 'App\\Repository\\PatientRepository',
        ]))->withContext('App\\Controller\\PatientController::index()', $container);
    }
}
