<?php

namespace ContainerXJV1m8A;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPatientControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bay_5P5.App\Controller\PatientController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Bay_5P5'] ?? $container->load('get_ServiceLocator_Bay5P5Service'));

        if (isset($container->privates['.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()'])) {
            return $container->privates['.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\PatientController::delete()', $container);

        if (isset($container->privates['.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()'])) {
            return $container->privates['.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()'];
        }

        return $container->privates['.service_locator.Bay_5P5.App\\Controller\\PatientController::delete()'] = $instance;
    }
}
