<?php

namespace ContainerXJV1m8A;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8AS6cEJ.App\Controller\RDVController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rdv' => ['privates', '.errored..service_locator.8AS6cEJ.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.8AS6cEJ": it needs an instance of "App\\Entity\\RDV" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
        ], [
            'rdv' => 'App\\Entity\\RDV',
            'em' => '?',
            'doctorRepository' => 'App\\Repository\\DoctorRepository',
            'patientRepository' => 'App\\Repository\\PatientRepository',
        ]))->withContext('App\\Controller\\RDVController::edit()', $container);

        if (isset($container->privates['.service_locator.8AS6cEJ.App\\Controller\\RDVController::edit()'])) {
            return $container->privates['.service_locator.8AS6cEJ.App\\Controller\\RDVController::edit()'];
        }

        return $container->privates['.service_locator.8AS6cEJ.App\\Controller\\RDVController::edit()'] = $instance;
    }
}
